### ISSUE TITLE
Schamper script failed to parse

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/hydra#206]
Processing http://www.schamper.ugent.be/2015-online/in-memoriam-alexander-baert
```
Traceback (most recent call last):
  File "schamper.py", line 172, in <module>
    process_schamper(API_PATH)
  File "schamper.py", line 25, in process_schamper
    transform_item_in_feed(item)
  File "schamper.py", line 62, in transform_item_in_feed
    author_node.string = _parse_article_authors(article)
  File "schamper.py", line 78, in _parse_article_authors
    raise Exception('Couldn\'t parse authors "{}"'.format(authors.text))
Exception: Couldn't parse authors "
          25 augustus 2015 om 15.56 uur
         "
```

**Comment by Procrat** [comment]
Ahja. Schamper hun artikels zijn kapot.
