### ISSUE TITLE
Error in cronjob

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/hydra#351]
```
Traceback (most recent call last):
  File "/home/hydra/deployment/20210207195348/scraper/resto/cafetaria.py", line 78, in <module>
    main(output_path)
  File "/home/hydra/deployment/20210207195348/scraper/resto/cafetaria.py", line 59, in main
    'breakfast': get_breakfast(),
  File "/home/hydra/deployment/20210207195348/scraper/resto/cafetaria.py", line 23, in get_breakfast
    ul = soup.find(id="content-core").find(name="ul")
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by niknetniko** [comment]
The breakfast menu seems to have disappeared; I'll create a PR.
